version = 1

exclude_patterns = [
  "StyleGAN2-ada/**/*",
  "stylegan2/**/*",
  "DeepFAMS/preprocessing.py",
  "DeepFAMS/run_training.py",
  "DeepFAMS/setup_training.py"
]


[[analyzers]]
name = "python"
enabled = false

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"
enabled = false
